<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'コンソール',
    'full_page' => '新しいウィンドウ',
    'close' => '閉じる',
    'start' => '起動',
    'restart' => '再起動',
    'stop' => '停止',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill はコンテナをその場で停止します。サーバーがまだディスクに書き込んでいないものはすべて失われます。続行しますか？',
    'sent_title' => '電源操作',
    'sent_body' => ':action を :name に送信しました。',
    'failed' => 'ノードに接続できませんでした。',
];
