<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Кансоль',
    'full_page' => 'Новае акно',
    'close' => 'Закрыць',
    'start' => 'Запусціць',
    'restart' => 'Перазапусціць',
    'stop' => 'Спыніць',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill спыняе кантэйнер адразу. Усё, што сервер яшчэ не запісаў на дыск, будзе страчана. Працягнуць?',
    'sent_title' => 'Дзеянне сілкавання',
    'sent_body' => ':action адпраўлена на :name.',
    'failed' => 'Не ўдалося звязацца з вузлом.',
];
