<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Konsoll',
    'full_page' => 'Nytt vindu',
    'close' => 'Lukk',
    'start' => 'Start',
    'restart' => 'Start på nytt',
    'stop' => 'Stopp',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill stopper containeren umiddelbart. Alt serveren ennå ikke har skrevet til disk, går tapt. Fortsette?',
    'sent_title' => 'Strømhandling',
    'sent_body' => ':action ble sendt til :name.',
    'failed' => 'Noden kunne ikke nås.',
];
