<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Console',
    'full_page' => 'Nouvelle fenêtre',
    'close' => 'Fermer',
    'start' => 'Démarrer',
    'restart' => 'Redémarrer',
    'stop' => 'Arrêter',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill arrête le conteneur sur-le-champ. Tout ce que le serveur n\'a pas encore écrit sur le disque est perdu. Continuer ?',
    'sent_title' => 'Action d\'alimentation',
    'sent_body' => ':action a été envoyé à :name.',
    'failed' => 'Le nœud est injoignable.',
];
