<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Konsole',
    'full_page' => 'Neues Fenster',
    'close' => 'Schließen',
    'start' => 'Starten',
    'restart' => 'Neu starten',
    'stop' => 'Stoppen',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill stoppt den Container sofort. Alles, was der Server noch nicht auf die Festplatte geschrieben hat, geht verloren. Fortfahren?',
    'sent_title' => 'Energieaktion',
    'sent_body' => ':action wurde an :name gesendet.',
    'failed' => 'Die Node war nicht erreichbar.',
];
