<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Konsol',
    'full_page' => 'Nyt vindue',
    'close' => 'Luk',
    'start' => 'Start',
    'restart' => 'Genstart',
    'stop' => 'Stop',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill stopper containeren med det samme. Alt, som serveren endnu ikke har skrevet til disken, går tabt. Fortsæt?',
    'sent_title' => 'Strømhandling',
    'sent_body' => ':action blev sendt til :name.',
    'failed' => 'Noden kunne ikke nås.',
];
