<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Конзола',
    'full_page' => 'Нов прозорец',
    'close' => 'Затвори',
    'start' => 'Стартирай',
    'restart' => 'Рестартирай',
    'stop' => 'Спри',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill спира контейнера на място. Всичко, което сървърът още не е записал на диска, се губи. Да продължим ли?',
    'sent_title' => 'Действие за захранване',
    'sent_body' => ':action беше изпратено към :name.',
    'failed' => 'Възелът не можа да бъде достигнат.',
];
