<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Console',
    'full_page' => 'Nuova finestra',
    'close' => 'Chiudi',
    'start' => 'Avvia',
    'restart' => 'Riavvia',
    'stop' => 'Arresta',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill arresta il container all\'istante. Tutto ciò che il server non ha ancora scritto su disco va perso. Continuare?',
    'sent_title' => 'Azione di alimentazione',
    'sent_body' => ':action è stato inviato a :name.',
    'failed' => 'Il nodo non è raggiungibile.',
];
