<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Consola',
    'full_page' => 'Ventana nueva',
    'close' => 'Cerrar',
    'start' => 'Iniciar',
    'restart' => 'Reiniciar',
    'stop' => 'Detener',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill detiene el contenedor de inmediato. Todo lo que el servidor aún no haya escrito en el disco se pierde. ¿Continuar?',
    'sent_title' => 'Acción de encendido',
    'sent_body' => ':action se envió a :name.',
    'failed' => 'No se pudo contactar con el nodo.',
];
