<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => '콘솔',
    'full_page' => '새 창',
    'close' => '닫기',
    'start' => '시작',
    'restart' => '다시 시작',
    'stop' => '중지',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill은 컨테이너를 즉시 중지합니다. 서버가 아직 디스크에 기록하지 않은 내용은 모두 사라집니다. 계속할까요?',
    'sent_title' => '전원 작업',
    'sent_body' => ':action을(를) :name에 보냈습니다.',
    'failed' => '노드에 연결할 수 없습니다.',
];
