<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Consola',
    'full_page' => 'Nova janela',
    'close' => 'Fechar',
    'start' => 'Iniciar',
    'restart' => 'Reiniciar',
    'stop' => 'Parar',
    'kill' => 'Kill',
    'kill_confirm' => 'O Kill pára o contentor de imediato. Tudo o que o servidor ainda não escreveu no disco perde-se. Continuar?',
    'sent_title' => 'Ação de energia',
    'sent_body' => ':action foi enviado para :name.',
    'failed' => 'Não foi possível contactar o nó.',
];
