<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'وحدة التحكم',
    'full_page' => 'نافذة جديدة',
    'close' => 'إغلاق',
    'start' => 'تشغيل',
    'restart' => 'إعادة تشغيل',
    'stop' => 'إيقاف',
    'kill' => 'إنهاء (Kill)',
    'kill_confirm' => 'الإنهاء يوقف الحاوية فوراً. كل ما لم يكتبه الخادم على القرص بعد سيُفقد. هل تريد المتابعة؟',
    'sent_title' => 'إجراء الطاقة',
    'sent_body' => 'تم إرسال :action إلى :name.',
    'failed' => 'تعذّر الوصول إلى العقدة.',
];
