<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => '主控台',
    'full_page' => '新視窗',
    'close' => '關閉',
    'start' => '啟動',
    'restart' => '重新啟動',
    'stop' => '停止',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill 會立即停止容器。伺服器尚未寫入磁碟的內容都會遺失。是否繼續？',
    'sent_title' => '電源操作',
    'sent_body' => '已將 :action 傳送至 :name。',
    'failed' => '無法連線至節點。',
];
