<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Konzol',
    'full_page' => 'Új ablak',
    'close' => 'Bezárás',
    'start' => 'Indítás',
    'restart' => 'Újraindítás',
    'stop' => 'Leállítás',
    'kill' => 'Kill',
    'kill_confirm' => 'A Kill azonnal leállítja a konténert. Minden, amit a szerver még nem írt lemezre, elvész. Folytatja?',
    'sent_title' => 'Bekapcsolási művelet',
    'sent_body' => 'A :action elküldve ide: :name.',
    'failed' => 'A csomópont nem volt elérhető.',
];
