<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Bảng điều khiển',
    'full_page' => 'Cửa sổ mới',
    'close' => 'Đóng',
    'start' => 'Khởi động',
    'restart' => 'Khởi động lại',
    'stop' => 'Dừng',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill dừng container ngay lập tức. Mọi thứ máy chủ chưa ghi xuống đĩa sẽ mất. Tiếp tục?',
    'sent_title' => 'Thao tác nguồn',
    'sent_body' => 'Đã gửi :action tới :name.',
    'failed' => 'Không liên lạc được với node.',
];
