<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Консоль',
    'full_page' => 'Нове вікно',
    'close' => 'Закрити',
    'start' => 'Запустити',
    'restart' => 'Перезапустити',
    'stop' => 'Зупинити',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill зупиняє контейнер негайно. Усе, що сервер ще не записав на диск, буде втрачено. Продовжити?',
    'sent_title' => 'Дія живлення',
    'sent_body' => ':action надіслано до :name.',
    'failed' => 'Не вдалося зв\'язатися з вузлом.',
];
