<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => 'Consolă',
    'full_page' => 'Fereastră nouă',
    'close' => 'Închide',
    'start' => 'Pornește',
    'restart' => 'Repornește',
    'stop' => 'Oprește',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill oprește containerul pe loc. Tot ce serverul nu a scris încă pe disc se pierde. Continuați?',
    'sent_title' => 'Acțiune de alimentare',
    'sent_body' => ':action a fost trimis către :name.',
    'failed' => 'Nodul nu a putut fi contactat.',
];
