<?php

/*
 * Generated by tools/make-lang.js as a starting point, not as a finished
 * translation. These are the strings every reader sees on pages they open
 * anyway - the power buttons and the node meters - so they were worth having in
 * every language Pelican supports before the rest of the plugin is done.
 *
 * Corrections from someone who actually speaks this are welcome and should be
 * made here; the generator skips files that already exist.
 *
 * A key missing from this file is not a fault. Laravel falls back per key, so
 * what is here is in this language and the rest is English.
 */

return [
    'console' => '控制台',
    'full_page' => '新窗口',
    'close' => '关闭',
    'start' => '启动',
    'restart' => '重启',
    'stop' => '停止',
    'kill' => 'Kill',
    'kill_confirm' => 'Kill 会立即停止容器。服务器尚未写入磁盘的内容都会丢失。是否继续？',
    'sent_title' => '电源操作',
    'sent_body' => '已将 :action 发送至 :name。',
    'failed' => '无法连接到节点。',
];
